/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author luzne
 */
public class Estadios extends javax.swing.JFrame {

    /**
     * Creates new form Estadios
     */
    public Estadios() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMaraca = new javax.swing.JButton();
        btnMonu = new javax.swing.JButton();
        btnMetro = new javax.swing.JButton();
        btnAtan = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMaraca.setBackground(new java.awt.Color(31, 66, 117));
        btnMaraca.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnMaraca.setForeground(new java.awt.Color(255, 255, 255));
        btnMaraca.setIcon(new javax.swing.ImageIcon("C:\\Users\\luzne\\OneDrive\\Documentos\\NetBeansProjects\\Mundial\\src\\main\\java\\imagenes\\e_mara.png")); // NOI18N
        btnMaraca.setText("Maracaná");
        btnMaraca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaracaActionPerformed(evt);
            }
        });
        jPanel1.add(btnMaraca, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 290, -1));

        btnMonu.setBackground(new java.awt.Color(31, 66, 117));
        btnMonu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnMonu.setForeground(new java.awt.Color(255, 255, 255));
        btnMonu.setIcon(new javax.swing.ImageIcon("C:\\Users\\luzne\\OneDrive\\Documentos\\NetBeansProjects\\Mundial\\src\\main\\java\\imagenes\\e_mas.png")); // NOI18N
        btnMonu.setText("Más Monumental");
        btnMonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonuActionPerformed(evt);
            }
        });
        jPanel1.add(btnMonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 310, 110));

        btnMetro.setBackground(new java.awt.Color(31, 66, 117));
        btnMetro.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnMetro.setForeground(new java.awt.Color(255, 255, 255));
        btnMetro.setIcon(new javax.swing.ImageIcon("C:\\Users\\luzne\\OneDrive\\Documentos\\NetBeansProjects\\Mundial\\src\\main\\java\\imagenes\\e_metro.png")); // NOI18N
        btnMetro.setText("Metropolitano");
        btnMetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetroActionPerformed(evt);
            }
        });
        jPanel1.add(btnMetro, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 310, -1));

        btnAtan.setBackground(new java.awt.Color(31, 66, 117));
        btnAtan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAtan.setForeground(new java.awt.Color(255, 255, 255));
        btnAtan.setIcon(new javax.swing.ImageIcon("C:\\Users\\luzne\\OneDrive\\Documentos\\NetBeansProjects\\Mundial\\src\\main\\java\\imagenes\\e_ata.png")); // NOI18N
        btnAtan.setText("Atanasio");
        btnAtan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtanActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 280, 110));

        jButton5.setBackground(new java.awt.Color(22, 50, 89));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\luzne\\OneDrive\\Documentos\\NetBeansProjects\\Mundial\\src\\main\\java\\imagenes\\volver.png")); // NOI18N
        jButton5.setText("Volver");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 120, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\luzne\\OneDrive\\Documentos\\NetBeansProjects\\Mundial\\src\\main\\java\\imagenes\\f_es.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMaracaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaracaActionPerformed
        E_maracana mara= new E_maracana();
        mara.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMaracaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Menu menu= new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnMetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetroActionPerformed
       E_metropolitano metro= new E_metropolitano();
        metro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMetroActionPerformed

    private void btnAtanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtanActionPerformed
        E_atanasio ata= new E_atanasio();
        ata.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtanActionPerformed

    private void btnMonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonuActionPerformed
        E_monumental monu= new E_monumental();
        monu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMonuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estadios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estadios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estadios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estadios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estadios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtan;
    private javax.swing.JButton btnMaraca;
    private javax.swing.JButton btnMetro;
    private javax.swing.JButton btnMonu;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
